Update layer configuration whenever a new layer is added.
AsteroidOS/asteroid pull request #247
Opened 2023-04-30 14:50 UTC by MagneFire

Previously one could provide a new platform to the `devices` variable. This implies a new layer under `src/meta-smartwatch/meta-*`. But the build configuration (bblayers.conf) is never updated with this new information as that file may already exists.

This adds support for updating the layer configuration whenever a new layer is added to the `layer_conf` variable and or a new layer becomes available in the `meta-smartwatch` repository.

2023-05-03 15:33 UTC, beroset requested changes
A few nits and suggestions.

2023-05-03 15:33 UTC, beroset commented on prepare-build.sh
> +"' > build/conf/bblayers.conf
This is a bit confusing to read.  An alternative approach that might be easier would be to pull the list of layers into an array with something like:
```
existing_layers=($(sed -nr 's/  \$\{SRCDIR\}\/(\S+) \\/\1/p' build/conf/bblayers.conf))
```
Then `update_layer_config` would only have to compare the two arrays to figure out what to add.

2023-05-03 21:35 UTC, MagneFire commented on prepare-build.sh
> +    IFS=$'\n' layers_smartwatch=($(find src/meta-smartwatch -mindepth 1 -name "*meta-*" -type d | sed -e 's|src/||' | sort))
`mapfile` isn't compatible with zsh. Currently one can execute this script under bash and zsh. Using mapfile would break this support.

2023-05-03 21:35 UTC, MagneFire commented on prepare-build.sh
> +        layer_line="  \${SRCDIR}/${layer} \\"
Fixed!

2023-05-03 21:35 UTC, MagneFire commented on prepare-build.sh
> +        grep -qxF "$layer_line" build/conf/bblayers.conf || sed -i "s@BBLAYERS = \" \\\\@BBLAYERS = \" \\\\\n$layer_line\\@" build/conf/bblayers.conf
Great idea! I've adjusted the script to now use `awk`.

2023-05-03 23:06 UTC, FlorentRevest approved these changes

2023-05-06 12:04 UTC, beroset approved these changes

2023-05-06 12:04 UTC, beroset commented on prepare-build.sh
> +    IFS=$'\n' layers_smartwatch=($(find src/meta-smartwatch -mindepth 1 -name "*meta-*" -type d | sed -e 's|src/||' | sort))
Ah, that's good to know.

2023-05-06 12:22 UTC, merged